[package]
name = "gravel_cli"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "gravel"
path = "src/main.rs"

[dependencies]
cracked_md = { path = "../cracked_md" }
stdsrv = { path = "../stdsrv" }
slogger = { path = "../slogger" }
